#!/bin/sh
set -e
case "$1" in
	remove)
		if [ -f /etc/cron.d/apt-auto-update ] && grep -q managed-by-apt-auto-update /etc/cron.d/apt-auto-update 2>/dev/null; then
			rm -f /etc/cron.d/apt-auto-update
		fi
		;;
esac
exit 0
